version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: db_inventario
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: inventario
    volumes:
      - inventario_data:/var/lib/postgresql/data

volumes:
  inventario_data:
